### ISSUE TITLE
Control statements lecture

### ISSUE THREAD

**Issue by mdisuanco** [theJollySin/python_for_scientists#55]
Under "Indentation", should those "return" statements be "print" statements since they are not being used within a function?

**Comment by john-science** [comment]
You know, in my head, those snippets of code were inside functions and classes. But you're right, that's not obvious from what was written. That is a lot more clear that way.

Good call!

**Comment by mdisuanco** [comment]
I can't take the credit. We had the first lecture on Tuesday and an eager student got to work on the examples in the lecture and had issues executing the code, initially thinking the error was due to indentation.

Thanks! The staff here really appreciate the material!

**Comment by john-science** [comment]
I'm just happy someone is still using the class.  How nice.
