### ISSUE TITLE
Solution in "01_control_statements/problem_set_1_solutions.md"

### ISSUE THREAD

**Issue by mdisuanco** [theJollySin/python_for_scientists#56]
1. Print the numbers 3 through 13 using a for loop and a range statement.
for i in range(1, 11):
    print(i)

I think the solution should be "range(3,14)" or "range(3,13+1)".

**Comment by john-science** [comment]
That's odd. I wonder how that snuck through for so long.

Thanks for the help!  It's great to have a second set of eyes on my *many* typos.
