### ISSUE TITLE
Reading csv in lecture 04 - Advanced Strings

### ISSUE THREAD

**Issue by XueMChen** [theJollySin/python_for_scientists#60]
In the Reading and Writing CSV Files section, python is not smart enough to convert '5e5' to integer.
Float() instead of int() would work, or have 50000, 100000, 4000000 written in the csv file as the last column of the last 3 rows instead of their scientific notation?

Happy Halloween~

**Comment by john-science** [comment]
Well, not sure how that slipped past by everyone for so long.  That's not even a Python 3 issue.  

Thanks for the find!
