### ISSUE TITLE
Type conversion in lecture 04 - Advanced Strings

### ISSUE THREAD

**Issue by XueMChen** [theJollySin/python_for_scientists#61]
We found an error during the lecture that is quite interesting:
bool("False") gives True, not False...
which is very counter-intuitive, but it does go with the statement earlier in the lecture that boolean of anything other than zero is True.

**Comment by john-science** [comment]
Yup, I have no idea what I would have written that.

    >>> bool("False")
    True
    >>> eval("False")
    False

Glad to hear you guys are working through the class again!  I'll fix this in a second.
