### ISSUE TITLE
matplotlib -- alpha=np.random.rand(N)

### ISSUE THREAD

**Issue by mdisuanco** [theJollySin/python_for_scientists#71]
Does this work...using an array of values for alpha? It didn't work for me...I think it only accepts a scalar.

**Comment by john-science** [comment]
Huh. It worked for me before. Maybe that's a Python 2 vs 3 difference? I will try in and see what I find.

**Comment by john-science** [comment]
Yup, at least in Python 3, it looks like you're right. Totally. I'll fix it.

Thanks!
Good find!
