### ISSUE TITLE
Mention f-strings in Advanced Strings lecture.

### ISSUE THREAD

**Issue by mrzachsnyder** [theJollySin/python_for_scientists#79]
There are many wonderful writeups, e.g. Google's first search result:
https://realpython.com/python-f-strings/

tl;dr embedding variables in your string is easier and more readable with f-strings.

Example using string.format()
`"{} minutes | ({}) Move {} assembly from {} to {}".format(travelTime, self.name, self.assyType, self.locationName, nextLocationName)`

Same example with f-string
`f"{travelTime} minutes | ({self.name}) Move {self.assyType} assembly from {self.locationName} to {nextLocationName}"`

**Comment by john-science** [comment]
This is a great idea!

**Comment by john-science** [comment]
Tell me if you like this (albeit short) introduction to f-strings!

https://github.com/john-science/python_for_scientists/commit/62a8b6e501665dd9671e390a154bf1d8352fc67e

I am happy to add to it, and build on it.

**Comment by mrzachsnyder** [comment]
Looks good to me, thank you for adding f-strings!
