### ISSUE TITLE
Incomplete answer in Lecture 05 PS 01

### ISSUE THREAD

**Issue by brrttnrth** [theJollySin/python_for_scientists#85]
In problem set 1 for [Lecture 05, "Lambda and Looping"](https://github.com/john-science/python_for_scientists/blob/c105073df5619fbebc4385a5be5ce6520ce2bff0/classes/05_lists_and_lambdas/lecture_05.md), the answer to number 3 in the "Filters" section does not account for even numbers as part of the answer.

### Question

https://github.com/john-science/python_for_scientists/blob/c105073df5619fbebc4385a5be5ce6520ce2bff0/classes/05_lists_and_lambdas/problem_set_1_map_reduce_filter.md?plain=1#L29

### Current Answer

https://github.com/john-science/python_for_scientists/blob/c105073df5619fbebc4385a5be5ce6520ce2bff0/classes/05_lists_and_lambdas/problem_set_1_solutions.md?plain=1#L48

**Comment by john-science** [comment]
Thanks!

Sure, I see, the current answer is:

```python
len(list(filter(lambda i: i % 99 == 0, range(1000000))))
```

But the real answer is:

```python
len(list(filter(lambda i: i % 99 == 0 and i % 2 == 0, range(1000000))))
```

**Comment by john-science** [comment]
Issue resolved with this commit:  https://github.com/john-science/python_for_scientists/commit/1c5e3d26abe17faf7d7c061d0d5e9e7793801cf6
