### ISSUE TITLE
Minor issues in lecture 17, testing projects 

### ISSUE THREAD

**Issue by AlexSupertrap** [theJollySin/python_for_scientists#86]
1. line 95 `if percent_grade >= 90.0` should have a `< 100` as well based on line 239
2. line 296, should be "to" instead of "two"
3. `student.py`, lines 61 to 105, should include a `main()` function based on later explanations.

**Comment by john-science** [comment]
Thanks!

**Comment by john-science** [comment]
Thank so much!

I fixed number (1) and (2) on your list above.

Number (3) actually, is not something that I'll do.  Essentially, there are two kinds of `*.py` files:

1. Scripts that are run from the command line (`python my_script.py`).  These need `main()` functions.
2. Scripts which just define code and are meant to be imported. Like our file that just contains the `Student` class.

The difference with our `Student` class, is it is not meant to be run from the command line. It is meant to be code that people import and use as they see fit.

Does that make sense?
