### ISSUE TITLE
Getting "404: Not Found" when trying to access the CSV at the start of the problem_set_1_scipy.md

### ISSUE THREAD

**Issue by AlexSupertrap** [theJollySin/python_for_scientists#91]
See tittle. The following link is dead: 

https://[raw.githubusercontent.com/john-sciecen/python_for_scientists/master/classes/11_scipy/london_2012_olympic_athlete_data.csv](https://raw.githubusercontent.com/john-sciecen/python_for_scientists/master/classes/11_scipy/london_2012_olympic_athlete_data.csv)

and is used on: 
https://github.com/john-science/python_for_scientists/blob/main/classes/11_scipy/problem_set_1_scipy.md

Thanks as always John! You are awesome!

**Comment by john-science** [comment]
Fixed!
